insert into Models (modelName, modelType) values ('A1', 'kombi')
insert into Models (modelName, modelType) values ('A1', 'sedan')
insert into Models (modelName, modelType) values ('A1', 'hatchback')
insert into Models (modelName, modelType) values ('A2', 'kombi')
insert into Models (modelName, modelType) values ('A2', 'sedan')
insert into Models (modelName, modelType) values ('A2', 'hatchback')
insert into Models (modelName, modelType) values ('A3', 'kombi')
insert into Models (modelName, modelType) values ('A3', 'sedan')
insert into Models (modelName, modelType) values ('A3', 'hatchback')
insert into Models (modelName, modelType) values ('A4', 'kombi')
insert into Models (modelName, modelType) values ('A4', 'sedan')
insert into Models (modelName, modelType) values ('A4', 'hatchback')
insert into Models (modelName, modelType) values ('A5', 'kombi')
insert into Models (modelName, modelType) values ('A5', 'sedan')
insert into Models (modelName, modelType) values ('A5', 'hatchback')
insert into Models (modelName, modelType) values ('A6', 'kombi')
insert into Models (modelName, modelType) values ('A6', 'sedan')
insert into Models (modelName, modelType) values ('A6', 'hatchback')
insert into Models (modelName, modelType) values ('A7', 'kombi')
insert into Models (modelName, modelType) values ('A7', 'sedan')
insert into Models (modelName, modelType) values ('A7', 'hatchback')
insert into Models (modelName, modelType) values ('A8', 'kombi')
insert into Models (modelName, modelType) values ('A8', 'sedan')
insert into Models (modelName, modelType) values ('A8', 'hatchback')
insert into Models (modelName) values ('Q1')
insert into Models (modelName) values ('Q2')
insert into Models (modelName) values ('Q3')
insert into Models (modelName) values ('Q4')
insert into Models (modelName) values ('Q5')
insert into Models (modelName) values ('Q6')
insert into Models (modelName) values ('Q7')
insert into Models (modelName) values ('Q8')

insert into Transmissions (transType, numOfGears) values ('Auto', 4)
insert into Transmissions (transType, numOfGears) values ('Auto', 5)
insert into Transmissions (transType, numOfGears) values ('Auto', 6)
insert into Transmissions (transType, numOfGears) values ('Auto', 8)
insert into Transmissions (transType, numOfGears) values ('Manual', 4)
insert into Transmissions (transType, numOfGears) values ('Manual', 5)
insert into Transmissions (transType, numOfGears) values ('Manual', 6)

INSERT into VehicleStates (state) VALUES(0)
INSERT into VehicleStates (state) VALUES(1)

insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 1, 95, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 1, 95, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 1, 95, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 1, 95, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 2, 256, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 2, 256, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 2, 256, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 2, 256, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 3, 427, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 3, 427, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 3, 427, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 3, 427, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 4, 439, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 4, 439, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 4, 439, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 4, 439, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 5, 577, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 5, 577, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 5, 577, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 5, 577, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 6, 888, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 6, 888, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 6, 888, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 6, 888, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 8, 1285, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 8, 1285, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 8, 1285, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 1, 8, 1285, 'euro6')

insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 1, 73, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 1, 73, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 1, 73, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 1, 73, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 2, 197, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 2, 197, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 2, 197, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 2, 197, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 3, 328, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 3, 328, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 3, 328, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 3, 328, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 4, 339, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 4, 339, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 4, 339, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 4, 339, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 5, 443, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 5, 443, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 5, 443, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 5, 443, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 6, 683, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 6, 683, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 6, 683, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 6, 683, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 8, 986, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 8, 986, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 8, 986, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('B', 0, 8, 986, 'euro6')

insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 2, 256, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 2, 256, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 2, 256, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 2, 256, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 3, 427, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 3, 427, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 3, 427, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 3, 427, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 4, 439, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 4, 439, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 4, 439, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 4, 439, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 5, 577, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 5, 577, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 5, 577, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 5, 577, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 6, 888, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 6, 888, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 6, 888, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 1, 6, 888, 'euro6')

insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 2, 197, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 2, 197, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 2, 197, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 2, 197, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 3, 328, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 3, 328, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 3, 328, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 3, 328, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 4, 339, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 4, 339, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 4, 339, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 4, 339, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 5, 443, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 5, 443, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 5, 443, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 5, 443, 'euro6')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 6, 683, 'euro3')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 6, 683, 'euro4')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 6, 683, 'euro5')
insert into Engines (fuelType, turbo, litres, hp, emissionStandart) values ('D', 0, 6, 683, 'euro6')
