SELECT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIE, MOVIEEXEC

SELECT * FROM MOVIE

SELECT * FROM MOVIEEXEC

SELECT * FROM MOVIESTAR

SELECT * FROM STARSIN

SELECT *
FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#

SELECT *
FROM MOVIE CROSS JOIN MOVIEEXEC

-- union, intersect, except, union all

(SELECT NAME, ADDRESS
FROM MOVIESTAR
WHERE GENDER = 'F')
INTERSECT
(SELECT NAME, ADDRESS
 FROM MOVIEEXEC)
 ORDER BY NAME

 SELECT NAME, ADDRESS
 FROM MOVIESTAR
 WHERE GENDER = 'F'


SELECT NAME
FROM MOVIESTAR


(SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE = 'The Usual Suspects')
INTERSECT
(SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M')


SELECT TITLE, STARNAME
FROM MOVIE JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE
WHERE MOVIEYEAR = 1995 AND STUDIONAME = 'MGM'

SELECT NAME FROM ships WHERE NAME LIKE '% %'

-------------------
-- Second exercise
-------------------
SELECT NAME
FROM STARSIN JOIN MOVIESTAR ON STARSIN.STARNAME = MOVIESTAR.NAME
WHERE GENDER = 'M' AND MOVIETITLE = 'The Usual Suspects'

SELECT STARNAME
FROM MOVIE JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE
WHERE YEAR = 1995 AND STUDIONAME = 'MGM'

SELECT DISTINCT NAME
FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE STUDIONAME = 'MGM'

SELECT TITLE
FROM (SELECT LENGTH 
      FROM MOVIE 
      WHERE TITLE = 'Star Wars') AS T JOIN MOVIE ON T.LENGTH < MOVIE.LENGTH

SELECT NAME
FROM (SELECT NETWORTH
      FROM MOVIEEXEC 
      WHERE NAME = 'Stephen Spielberg') AS T JOIN MOVIEEXEC ON T.NETWORTH < MOVIEEXEC.NETWORTH

SELECT TITLE
FROM (SELECT *
      FROM (SELECT NETWORTH AS BIGGEST
            FROM MOVIEEXEC 
            WHERE NAME = 'Stephen Spielberg') AS T JOIN MOVIEEXEC ON T.BIGGEST < MOVIEEXEC.NETWORTH)
            AS T1 JOIN MOVIE ON T1.CERT# = MOVIE.PRODUCERC#

SELECT MAKER, SPEED
FROM product JOIN laptop ON product.model = laptop.model
WHERE hd >= 9

SELECT T.model, T.price
FROM product JOIN (
    SELECT laptop.model, laptop.price
    FROM laptop
    UNION
    SELECT pc.model, pc.price
    FROM pc
    UNION
    SELECT printer.model, printer.price
    FROM printer
) as T ON product.model = T.model
WHERE maker = 'B'

SELECT product.maker from product join laptop on product.model = laptop.model
EXCEPT
SELECT product.maker from product join pc on product.model = pc.model

SELECT pc.hd 
from pc
GROUP BY pc.hd
HAVING COUNT(pc.hd) >= 2

select distinct t.model, pc.model from pc
CROSS JOIN pc as t
WHERE pc.hd = t.hd AND pc.speed = t.speed AND t.model > pc.model

select distinct maker
from product join pc on product.model = pc.model
where speed >= 400
group by speed, maker
HAVING COUNT(pc.speed) >= 2

select NAME
from ships join CLASSES on CLASSES.CLASS = ships.CLASS
where DISPLACEMENT > 50000

SELECT NAME, DISPLACEMENT, NUMGUNS
from CLASSES join ships on CLASSES.CLASS = ships.CLASS
            join OUTCOMES on ships.NAME = OUTCOMES.SHIP
where BATTLE = 'Guadalcanal'

SELECT  CLASSES.COUNTRY
from CLASSES CROSS JOIN CLASSES as T
where CLASSES.TYPE = 'bb' AND T.TYPE = 'bc' AND CLASSES.COUNTRY = T.COUNTRY

SELECT f.SHIP from
(SELECT SHIP, RESULT, DATE
from OUTCOMES JOIN BATTLES on OUTCOMES.BATTLE = BATTLES.NAME) as f
CROSS JOIN
(SELECT SHIP, RESULT, DATE
from OUTCOMES JOIN BATTLES on OUTCOMES.BATTLE = BATTLES.NAME) as s
where f.SHIP = s.SHIP AND f.[DATE] < s.[DATE]